[project]
name = "hash-cache"
authors = ["Your Name <your.email@example.com>"]
description = "Decentralized data verification and caching system"
telemetry = false
requirements = []

[contracts.hash-registry]
path = "contracts/hash-registry.clar"
depends_on = []

[contracts.hash-access]
path = "contracts/hash-access.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
